### ISSUE TITLE
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by davidfrtala** [happylynx/flow-webpack-plugin#2]
Hello,

I am unable to run this plugin. I followed the step process on readme, and after starting webpack it crashes immediately

> /path/to/app/node_modules/flow-webpack-plugin/dist/index.js:22
> let errorToReport = undefined
>   ^^^
> 
>   SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
> at exports.runInThisContext (vm.js:53:16)
> at Module._compile (module.js:387:25)
> at Module._extensions..js (module.js:422:10)
> at Object.require.extensions.(anonymous function) [as .js] (/path/to/app/node_modules/babel-register/lib/node.js:152:7)
> at Module.load (module.js:357:32)
> at Function.Module._load (module.js:314:12)
> at Module.require (module.js:367:17)
> at require (internal/module.js:16:19)
> at Object.<anonymous> (/path/to/app/webpack/dev.js:8:1)
> at Module._compile (module.js:413:34)
> at loader (/path/to/app/node_modules/babel-register/lib/node.js:144:5)
> at Object.require.extensions.(anonymous function) [as .js] (/path/to/app/node_modules/babel-register/lib/node.js:154:7)
> at Module.load (module.js:357:32)
> at Function.Module._load (module.js:314:12)
> at Module.require (module.js:367:17)
> at require (internal/module.js:16:19)

My current dependencies are listed bellow

> "devDependencies": {
>   ...
>   "flow-bin": "^0.40.0",
>   "flow-webpack-plugin": "^0.3.6",
>   "webpack": "^2.2.1",
> }

**Comment by MikaAK** [comment]
Having the same issue, moved to https://www.npmjs.com/package/flow-babel-webpack-plugin which works fine. 

Note:
I'm on node 5.12 which is 100% why this is happening. Even adding `use strict` is not enough because this lib uses rest parameters. Either this will need to be transpiled or you will need to be on node 6.x.

**Comment by happylynx** [comment]
As mentioned in https://github.com/happylynx/flow-webpack-plugin/issues/2#issuecomment-286939632, this plugin uses syntax that is not support by node 5, which I assume you are using. Please upgrade to current version of node (or at least node 6).
