### ISSUE TITLE
Extra flow validation errors

### ISSUE THREAD

**Issue by jestanoff** [happylynx/flow-webpack-plugin#3]
When there are flow errors coming from flowOutput I always get extra errors following webpack bundle stats. These particular errors should have been resolved by mapping 'less' in `.flowconfig` but for some reason I still get them here. If I fix all flow errors I don't get these extra errors. If run `flow status` there are only the regular error messages. 

Webpack is still running and the plugin is not failing but I should scroll my terminal every single time to check what I need to see.

![image](https://cloud.githubusercontent.com/assets/2598484/26687640/2e014d0c-46e8-11e7-9462-2a275fd74b5a.png)

```
#.flowconfig
[ignore]
<PROJECT_ROOT>/www/.*
<PROJECT_ROOT>/gulp/.*
<PROJECT_ROOT>/tests/.*
[include]
<PROJECT_ROOT>/src/.*
[libs]
flow-typed
[options]
module.file_ext=.js
server.max_workers=3
module.name_mapper.extension='less' -> '<PROJECT_ROOT>/flow/CSSModule.js.flow'
module.name_mapper.extension='sass' -> '<PROJECT_ROOT>/flow/CSSModule.js.flow'
module.name_mapper.extension='css' -> '<PROJECT_ROOT>/flow/CSSModule.js.flow'
module.name_mapper.extension='png' -> '<PROJECT_ROOT>/flow/WebpackAsset.js.flow'
module.name_mapper.extension='jpg' -> '<PROJECT_ROOT>/flow/WebpackAsset.js.flow'
module.name_mapper.extension='jpeg' -> '<PROJECT_ROOT>/flow/WebpackAsset.js.flow'
module.name_mapper.extension='gif' -> '<PROJECT_ROOT>/flow/WebpackAsset.js.flow'
esproposal.class_static_fields=enable
esproposal.class_instance_fields=enable
```
using:
node@v7.10.0
flow-webpack-plugin@0.3.6

**Comment by happylynx** [comment]
Hi @jestanoff, could you please attach corresponding `webpack.config.js`?
